#! /bin/bash

DOCKER_IMAGE_NAME=myISBG
DOCKER_IMAGE_TAG=latest
IMAPUSER=example
CONTAINER_VOLUMES_DIR=${PWD}/data


docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

mkdir ${CONTAINER_VOLUMES_DIR}/spamassassin 2>/dev/null
mkdir ${CONTAINER_VOLUMES_DIR}/accounts 2>/dev/null

docker run -d --rm --name isbg_${IMAPUSER} \
	-v ${CONTAINER_VOLUMES_DIR}/spamassassin:/var/spamassassin \
	-v ${CONTAINER_VOLUMES_DIR}/accounts:/root/accounts \
	$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
